---

- name: database setup
  hosts: database
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    - mysql

- name: fedora setup
  hosts: fedora
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    - tomcat7
    - fcrepo4

- name: camel setup
  hosts: camel
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    # - tomcat7
    - camel
    - fcrepo-camel

- name: solr setup
  hosts: solr
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    - tomcat7
    - solr

- name: fuseki setup
  hosts: fuseki
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    - fuseki

- name: webserver setup
  hosts: webserver
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    - apache
    - drupal
    - islandora

# and at the end would be djatoka
