---

- name: vagrant optimization
  hosts: all
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common

  post_tasks:
    - set_fact:
        common_required: false

- name: database setup
  hosts: database
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    - postgres

# hosts: memcache

- name: fedora setup
  hosts: fedora
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    - fcrepo4

- name: sync setup
  hosts: sync
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    - sync

- name: solr setup
  hosts: solr
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    - solr

- name: fuseki setup
  hosts: fuseki
  remote_user: "{{ deploy_user }}"
  sudo: yes

  roles:
    - common
    - fuseki

# NEED TO HAVE GATHERED DB FACTS [--limit=database,webserver]
# NEED TO HAVE PROVIDED ACCESS TO DB FROM WEBSERVER [SEE DB CONFIG]
- name: webserver setup
  hosts: webserver
  remote_user: "{{ deploy_user }}"
  sudo: yes

  pre_tasks:
    - name: create site postgres database user
      postgresql_user:
        login_host: "{{ hostvars[item.db.hostname]['ansible_' + private_network_interace]['ipv4']['address'] }}"
        login_user: postgres
        login_password: "{{ postgresql_pg_password }}"
        name: "{{ item.db.name }}"
        password: "{{ item.db.password }}"
        role_attr_flags: "SUPERUSER,INHERIT,NOCREATEDB,NOCREATEROLE,NOREPLICATION"
      with_items: drupal_sites
      tags:
        - postgresql
        - drupal

    - name: create site postgres database
      postgresql_db:
        login_host: "{{ hostvars[item.db.hostname]['ansible_' + private_network_interace]['ipv4']['address'] }}"
        login_user: postgres
        login_password: "{{ postgresql_pg_password }}"
        name: "{{ item.db.name }}"
        owner: "{{ item.db.name }}"
      with_items: drupal_sites
      tags:
        - postgresql
        - drupal

  roles:
    - common
    - islandora

# hosts: load-balancer

# hosts: djatoka
