---

- name: download fcrepo-camel
  sudo: no
  local_action: >
    get_url
    url="{{ fcrepo_camel_download_url }}"
    dest="bin/{{ fcrepo_camel_bin }}"
  tags:
   - fcrepo-camel

- name: create fcrepo-camel home
  file:
    path: "{{ fcrepo_camel_home }}"
    state: directory
    owner: tomcat7
    group: tomcat7
  tags:
   - fcrepo-camel

- name: copy fcrepo-camel to server
  copy:
    src: "bin/{{ fcrepo_camel_bin }}"
    dest: "{{ fcrepo_camel_home }}/{{ fcrepo_camel_bin }}"
    owner: tomcat7
    group: tomcat7
  tags:
   - fcrepo-camel
