---

- name: download camel
  sudo: no
  local_action: >
    get_url
    url="{{ camel_download_url }}"
    dest="bin/{{ camel_bin }}"
  tags:
   - camel

- name: install required packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - openjdk-7-jdk
    - ant
    - maven
  tags:
    - camel

- name: create camel package directory
  file:
    path: /opt/camel
    state: directory
  tags:
   - camel

- name: copy camel to server
  unarchive:
    src: "bin/{{ camel_bin }}"
    dest: "/opt/camel"
    creates: "/opt/camel/{{ camel_pkg }}"
  tags:
   - camel

- name: re/set camel directory permissions
  file:
    path: /opt/camel
    owner: tomcat7
    group: tomcat7
    state: directory
    recurse: yes
  tags:
   - camel

- name: symlink camel home
  file:
    src: "/opt/camel/{{ camel_pkg }}"
    dest: "{{ camel_home }}"
    state: link
  tags:
   - camel
