---

# drupal_profiles:
#   -
#     name: islf4
#     url: https://github/drupal-islf4-profile.git

# passwords would really be encrypted and included via:
# {{ SITE_password }} {{ SITE_salt }} {{ SITE_db_password }}
drupal_sites:
  -
    # drupal site dir
    site: default
    profile: standard # update to islf4
    name: Islandora Fedora 4
    domain: islandora-fedora4.org
    password: islandora
    salt: U8aNDD9F9PtsH3Gazyj9eGuM
    # sites.php mappings (include domain)
    aliases:
      - islandora-fedora4.org
      - islf4.vagrant
    modules: []
      # -
      #   name: islf4_features
      #   url: https://github/drupal-islf4-features.git
    db:
      driver: pgsql
      hostname: islf4-db
      name: islf4
      password: islandora
