---

# drupal_profiles:
#   -
#     name: islf4
#     url: https://github/drupal-islf4-profile.git

islandora_modules_path: "{{ drupal_path }}/sites/all/modules"

# suppose there's a master repository containing all modules
islandora_modules:
  -
    name: islandora
    url: https://github/islandora_modules.git
    path: "{{ islandora_modules_path }}"

islandora_custom_modules:
  -
    name: islf4_features
    url: https://github/drupal-islf4-features.git
    path: "sites/default/modules"

# passwords would really be encrypted and included via:
# {{ SITE_password }} {{ SITE_salt }} {{ SITE_db_password }}
drupal_sites:
  -
    # drupal site dir
    site: default
    profile: standard # update to islf4
    name: Islandora Fedora 4
    domain: islandora-fedora4.org
    password: islandora
    salt: U8aNDD9F9PtsH3Gazyj9eGuM
    aliases:
      - islf4.vagrant
    modules: []
      # with_flattened provides std way to iterate through all elements
      # - islandora_modules
      # - islandora_custom_modules
    db:
      driver: pgsql
      hostname: islf4-db
      name: islf4
      password: islandora
