---

drupal_sites:
  -
    # drupal site dir
    code: default
    name: Islandora Fedora 4
    domain: islandora-fedora4.org
    password: islandora
    # sites.php mappings (include domain)
    aliases:
      - islandora-fedora4.org
      - islf4.vagrant
    db:
      driver: pgsql
      hostname: islf4-db
      name: islf4
      password: islandora
