---

drupal_profiles:
  -
    name: islf4
    url: https://github.com/mark-cooper/islf4_profile.git

# tmp: symlink
drupal_local_modules:
  -
    path: /vagrant/bin/islandora/drupal
    dest: sites/all/modules/islandora

# suppose there's a master repository containing all modules
# drupal_remote_modules:
#   -
#     name: islandora
#     url: https://github/islandora_modules.git

# passwords would really be encrypted and included via:
# {{ SITE_password }} {{ SITE_salt }} {{ SITE_db_password }}
drupal_sites:
  -
    # drupal site dir
    site: default
    profile: islf4 # update to islf4
    name: Islandora Fedora 4
    domain: islandora-fedora4.org
    password: islandora
    salt: U8aNDD9F9PtsH3Gazyj9eGuM
    aliases:
      - islf4.vagrant
    modules:
      -
        name: islf4_features
        url: https://github.com/mark-cooper/islf4_features.git
        type: modules
      # -
      #   name: islf4_theme
      #   url: https://github/drupal-islf4-theme.git
      #   type: themes
    db:
      driver: pgsql
      hostname: islf4-db
      name: islf4
      password: islandora
