---

- name: install required packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "openjdk-7-{{ tomcat7_java_type }}"
    - tomcat7
  tags:
    - tomcat7
